### PR TITLE
Add loadFile' which returns envs, not loading them

### PR DESCRIPTION
**Pull request by fujimura**
I'm creating a Foreman clone in Haskell now, and need this function in it. Thanks!

### CODE REVIEW

**Comment by jsl** [comment]
@fujimura merged, and thanks for your contribution. Our team is interested in your work on creating a foreman clone, and it's something we may be interested in helping with. If you wouldn't mind, please drop me an email sometime if you'd be willing to discuss your work. Thanks again!

**Comment by jsl** [comment]
@fujimura please note that I changed the function name to be a bit more descriptive, and to follow conventions in similar libraries such as the Python dotenv library. You will find the function that you added by the name `parseFile` in the 0.2.0.0 release on Hackage. Thanks again for your contribution!

**Comment by fujimura** [comment]
Thanks! The code is here: https://github.com/fujimura/houseman. It's still work in progress and lacks many features available in foreman, but I'm already using this in daily work.

As for the naming, `parseFile` looks more better and correct. Thanks for fixing it!

**Comment by fujimura** [comment]
@jsl 
Just FYI, I've just uploaded first version of my foreman clone written in Haskell! I'm already using it in my daily job(Rails) and looks like it's working well at this moment. Contribution & collaboration are of course welcomed :)
http://hackage.haskell.org/package/houseman

**Pull request merged**
