### PR TITLE
Add stack and change .gitignore

### PR DESCRIPTION
**Pull request by CristhianMotoche**
@jsl Could you take a look?
- First, I added stack configuration in order to upload it to Stackage.
- Second, I had to add the capability to set empty environmental variables using System.Posix.Env, because the setEnv function from System.Environment.Compat has an issue when try to set an environmental variable with an empty string (you can read it here http://hackage.haskell.org/package/base-compat-0.8.2/docs/System-Environment-Compat.html#v:setEnv). I wrote three unit test in order to test this.

### CODE REVIEW

**Comment by jsl** [comment]
Hi @CristhianMotoche thanks for the contribution. I have one question - don't we want this package to compile on Windows any more? It seems like bringing in the Unix dependency will break compatibility with that platform, doesn't it?

**Comment by CristhianMotoche** [comment]
Yes, you're right. I think I could fix it with options that affect the C pre-processor. Could you tell me if that sounds like a good idea? I'll test it in a computer with Windows, and I'll tell you if that works. Thanks.

**Comment by jsl** [comment]
What is the problem you're trying to solve? I may be able to help if I
better understand what you're trying to do.
>
>

-- 
Justin Leitgeb <http://justinleitgeb.com>
Twitter: @justinleitgeb <http://twitter.com/justinleitgeb>
Github: @jsl <https://github.com/jsl>

Co-Founder and CTO, Stack Builders Inc. <http://www.stackbuilders.com>

**Comment by CristhianMotoche** [comment]
Oh, well the problem is with `setEnv` function which does `unsetEnv key` when the value for some key is empty (e.g. `setEnv "FOO" ""` won't set the environmental variable FOO, because the value is empty), that's because in Windows empty environmental variables don't exist.

**Comment by CristhianMotoche** [comment]
Oh, the problem is with `setEnv` function which does `unsetEnv key` when the value for some key is empty (e.g. `setEnv "FOO" ""` won't set the environmental variable FOO, because the value is empty), that's because in Windows empty environmental variables don't exist.

**Comment by jsl** [comment]
Right but to preserve compatibility with Windows, is that something we
can/want to change?

At any rate, seems like a separate issue from adding this package to stack.
What do you think about opening an issue on this repo to discuss, and
keeping this pr stack-specific so that we can merge it?

>

-- 
Justin Leitgeb <http://justinleitgeb.com>
Twitter: @justinleitgeb <http://twitter.com/justinleitgeb>
Github: @jsl <https://github.com/jsl>

Co-Founder and CTO, Stack Builders Inc. <http://www.stackbuilders.com>

**Comment by CristhianMotoche** [comment]
Hey, I just tried it on Windows. It works, and I opened a new PR. May you can see it?

**Pull request merged**
